name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
      - name: Checkout 
      - uses: actions/checkout@v3

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-      

      - name: Function test
        run: clojure -Mkaocha
        working-directory: ./functions
      - name: Basic async test
        run: clojure -Mtest
        working-directory: ./projects/basic-async
      - name: Graphql async test
        run: clojure -Mtest --config-file ../test-shared/tests.edn --reporter kaocha.report/documentation features
        working-directory: ./projects/gql-async
